[package]
name = "check_bp512"
version = "0.1.0"
authors = ["Julius Hermelink <julius.hermelink@unibw.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "check_bp512"
crate-type = ["cdylib"]

[dependencies]
rustfft = "5.0.1"
crossbeam = "0.8.0"
libm = "0.2.7"

[dependencies.pyo3]
version = "0.15.1"

[features]
kyber512 = []
extension-module = ["pyo3/extension-module"]
default = ["extension-module", "kyber512"]

[dependencies.belief_propagation]
git = "https://github.com/ppopdesk/belief_propagation_lib.git"
branch = "ABP"
features = []

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
